### ISSUE TITLE
Failed to analyze declaration ItemRepositoryInitializer

### ISSUE THREAD

**Issue by nelsieborja** [pgrimard/spring-boot-react#2]
Below is the detailed error.. Please can you advise for the fix...

[ERROR] org.jetbrains.kotlin.util.KotlinFrontEndException: Front-end Internal error: Failed to analyze declaration ItemRepositoryInitializer
Cause: Unable to make field private static final jdk.internal.misc.Unsafe jdk.internal.misc.Unsafe.theUnsafe accessible: module java.base does not "opens jdk.internal.misc" to unnamed module @78cfa264

**Comment by pgrimard** [comment]
This sample project was built on Java 8.  It looks like you're trying to use Java 9 modules, which hasn't been tested on this project.
